// Jaipur Famous Places Data - Complete Monuments
const jaipurPlaces = [
    {
        id: 1,
        name: "Hawa Mahal",
        image: "https://picsum.photos/seed/hawamahal/400/300.jpg",
        description: "The Palace of Winds, a stunning five-story palace with 953 small windows (jharokhas) built for royal ladies to observe street festivals",
        openingTime: "9:00 AM - 4:30 PM",
        ticketPrice: "₹50 (Indians), ₹200 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=Hawa+Mahal,Jaipur",
        bestTime: "October to March",
        duration: "1-2 hours",
        builtBy: "Maharaja Sawai Pratap Singh",
        builtIn: "1799",
        architecture: "Rajputana with Islamic Mughal",
        significance: "UNESCO World Heritage Site",
        photography: "Allowed",
        facilities: ["Parking", "Audio Guide", "Museum", "Restrooms"]
    },
    {
        id: 2,
        name: "Amber Fort",
        image: "https://picsum.photos/seed/amberfort/400/300.jpg",
        description: "A magnificent fort-palace complex known for its artistic Hindu style elements, mirror palaces, and grand ramparts",
        openingTime: "8:00 AM - 5:30 PM",
        ticketPrice: "₹100 (Indians), ₹500 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=Amber+Fort,Jaipur",
        bestTime: "October to March",
        duration: "3-4 hours",
        builtBy: "Raja Man Singh",
        builtIn: "1592",
        architecture: "Hindu Rajputana with Mughal influences",
        significance: "Largest fort in Rajasthan",
        photography: "Allowed",
        facilities: ["Elephant Ride", "Light Show", "Parking", "Restaurant", "Restrooms"]
    },
    {
        id: 3,
        name: "City Palace",
        image: "https://picsum.photos/seed/citypalace/400/300.jpg",
        description: "The royal residence of the Maharaja of Jaipur, featuring beautiful courtyards, museums, and the Chandra Mahal",
        openingTime: "9:30 AM - 5:00 PM",
        ticketPrice: "₹200 (Indians), ₹700 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=City+Palace,Jaipur",
        bestTime: "October to March",
        duration: "2-3 hours",
        builtBy: "Maharaja Sawai Jai Singh II",
        builtIn: "1727",
        architecture: "Blend of Rajputana and Mughal",
        significance: "Still residence of royal family",
        photography: "Allowed (extra charge for museum)",
        facilities: ["Museum", "Art Gallery", "Parking", "Gift Shop", "Restrooms"]
    },
    {
        id: 4,
        name: "Jantar Mantar",
        image: "https://picsum.photos/seed/jantarmantar/400/300.jpg",
        description: "An astronomical observatory with the world's largest stone sundial and 19 architectural astronomical instruments",
        openingTime: "9:00 AM - 4:30 PM",
        ticketPrice: "₹50 (Indians), ₹200 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=Jantar+Mantar,Jaipur",
        bestTime: "October to March",
        duration: "1-2 hours",
        builtBy: "Maharaja Sawai Jai Singh II",
        builtIn: "1734",
        architecture: "Marble and stone astronomical instruments",
        significance: "UNESCO World Heritage Site",
        photography: "Allowed",
        facilities: ["Guided Tours", "Audio Guide", "Parking", "Restrooms"]
    },
    {
        id: 5,
        name: "Nahargarh Fort",
        image: "https://picsum.photos/seed/nahargarh/400/300.jpg",
        description: "A historic fort offering panoramic views of Jaipur city, especially beautiful during sunset",
        openingTime: "10:00 AM - 5:30 PM",
        ticketPrice: "₹50 (Indians), ₹200 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=Nahargarh+Fort,Jaipur",
        bestTime: "October to March",
        duration: "2-3 hours",
        builtBy: "Maharaja Sawai Jai Singh II",
        builtIn: "1734",
        architecture: "Rajputana military architecture",
        significance: "Part of Jaipur's defense system",
        photography: "Allowed",
        facilities: ["Restaurant", "View Point", "Parking", "Restrooms"]
    },
    {
        id: 6,
        name: "Jaigarh Fort",
        image: "https://picsum.photos/seed/jaigarh/400/300.jpg",
        description: "Home to the world's largest cannon on wheels, Jaivana, and extensive water reservoirs",
        openingTime: "9:00 AM - 4:30 PM",
        ticketPrice: "₹50 (Indians), ₹200 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=Jaigarh+Fort,Jaipur",
        bestTime: "October to March",
        duration: "2-3 hours",
        builtBy: "Maharaja Sawai Jai Singh II",
        builtIn: "1726",
        architecture: "Military fortification",
        significance: "Never conquered in battle",
        photography: "Allowed",
        facilities: ["Museum", "Cannon Display", "Parking", "Restrooms"]
    },
    {
        id: 7,
        name: "Albert Hall Museum",
        image: "https://picsum.photos/seed/alberthall/400/300.jpg",
        description: "The oldest museum of Rajasthan, showcasing Indo-Saracenic architecture and extensive collections",
        openingTime: "9:00 AM - 5:00 PM",
        ticketPrice: "₹40 (Indians), ₹300 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=Albert+Hall+Museum,Jaipur",
        bestTime: "October to March",
        duration: "1-2 hours",
        builtBy: "Maharaja Sawai Ram Singh",
        builtIn: "1876",
        architecture: "Indo-Saracenic",
        significance: "State museum of Rajasthan",
        photography: "Allowed (extra charge)",
        facilities: ["Museum", "Library", "Parking", "Restrooms"]
    },
    {
        id: 8,
        name: "Birla Mandir",
        image: "https://picsum.photos/seed/birlamandir/400/300.jpg",
        description: "A beautiful white marble temple dedicated to Lord Vishnu and Goddess Lakshmi with intricate carvings",
        openingTime: "6:00 AM - 12:00 PM, 3:00 PM - 9:00 PM",
        ticketPrice: "Free",
        mapLocation: "https://maps.google.com/?q=Birla+Mandir,Jaipur",
        bestTime: "October to March",
        duration: "1 hour",
        builtBy: "B.M. Birla Foundation",
        builtIn: "1988",
        architecture: "Modern marble temple",
        significance: "Important religious site",
        photography: "Allowed",
        facilities: ["Parking", "Prayer Hall", "Restrooms"]
    },
    {
        id: 9,
        name: "Jal Mahal",
        image: "https://picsum.photos/seed/jalmahal/400/300.jpg",
        description: "A romantic palace in the middle of Man Sagar Lake, appearing to float on water during monsoon",
        openingTime: "6:00 AM - 6:00 PM",
        ticketPrice: "View from outside only",
        mapLocation: "https://maps.google.com/?q=Jal+Mahal,Jaipur",
        bestTime: "October to March",
        duration: "30 minutes (viewing)",
        builtBy: "Maharaja Sawai Jai Singh II",
        builtIn: "1734",
        architecture: "Rajputana style",
        significance: "Hunting lodge for royal duck shooting parties",
        photography: "Allowed (from outside)",
        facilities: ["Boating", "View Point", "Parking", "Food Stalls"]
    },
    {
        id: 10,
        name: "Govind Dev Ji Temple",
        image: "https://picsum.photos/seed/govinddevji/400/300.jpg",
        description: "An ancient temple dedicated to Lord Krishna, known for beautiful architecture and religious ceremonies",
        openingTime: "5:30 AM - 12:00 PM, 4:00 PM - 9:00 PM",
        ticketPrice: "Free",
        mapLocation: "https://maps.google.com/?q=Govind+Dev+Ji+Temple,Jaipur",
        bestTime: "October to March",
        duration: "1 hour",
        builtBy: "Maharaja Sawai Jai Singh II",
        builtIn: "1735",
        architecture: "Rajasthani temple style",
        significance: "Important Krishna temple",
        photography: "Not allowed inside sanctum",
        facilities: ["Parking", "Prasad Counter", "Restrooms"]
    },
    {
        id: 11,
        name: "Moti Dungri Ganesh Temple",
        image: "https://picsum.photos/seed/motidungri/400/300.jpg",
        description: "An ancient temple dedicated to Lord Ganesha, believed to protect the city",
        openingTime: "5:00 AM - 10:00 PM",
        ticketPrice: "Free",
        mapLocation: "https://maps.google.com/?q=Moti+Dungri+Ganesh+Temple,Jaipur",
        bestTime: "October to March",
        duration: "45 minutes",
        builtBy: "Maharaja Sawai Jai Singh II",
        builtIn: "1761",
        architecture: "Traditional Rajasthani",
        significance: "Guardian deity of Jaipur",
        photography: "Allowed",
        facilities: ["Parking", "Prasad Counter", "Restrooms"]
    },
    {
        id: 12,
        name: "Isarlat Tower",
        image: "https://picsum.photos/seed/isarlat/400/300.jpg",
        description: "A 60-foot tall tower offering panoramic views of Pink City from Tripolia Bazaar",
        openingTime: "9:00 AM - 5:00 PM",
        ticketPrice: "₹30 (Indians), ₹100 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=Isarlat+Tower,Jaipur",
        bestTime: "October to March",
        duration: "30 minutes",
        builtBy: "Maharaja Sawai Ishwari Singh",
        builtIn: "1749",
        architecture: "Rajputana watchtower",
        significance: "Highest tower in old city",
        photography: "Allowed",
        facilities: ["View Point", "Parking", "Restrooms"]
    },
    {
        id: 13,
        name: "Sisodia Rani Garden",
        image: "https://picsum.photos/seed/sisodiargarden/400/300.jpg",
        description: "A beautiful terraced garden built for royal ladies, with fountains and pavilions",
        openingTime: "9:00 AM - 5:00 PM",
        ticketPrice: "₹20 (Indians), ₹50 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=Sisodia+Rani+Garden,Jaipur",
        bestTime: "October to March",
        duration: "1 hour",
        builtBy: "Maharaja Sawai Jai Singh II",
        builtIn: "1728",
        architecture: "Mughal garden style",
        significance: "Royal garden for queens",
        photography: "Allowed",
        facilities: ["Garden", "Fountains", "Parking", "Restrooms"]
    },
    {
        id: 14,
        name: "Galtaji Temple",
        image: "https://picsum.photos/seed/galtaji/400/300.jpg",
        description: "An ancient Hindu pilgrimage site with natural springs and temples in a mountain gorge",
        openingTime: "5:00 AM - 9:00 PM",
        ticketPrice: "Free",
        mapLocation: "https://maps.google.com/?q=Galtaji+Temple,Jaipur",
        bestTime: "October to March",
        duration: "2-3 hours",
        builtBy: "Ancient",
        builtIn: "18th century",
        architecture: "Traditional temple complex",
        significance: "Monkey temple with natural springs",
        photography: "Allowed",
        facilities: ["Natural Springs", "Temples", "Parking", "Food Stalls"]
    },
    {
        id: 15,
        name: "Kanak Vrindavan Garden",
        image: "https://picsum.photos/seed/kanakvrindavan/400/300.jpg",
        description: "A beautifully landscaped garden near Amber Fort with marble temples and fountains",
        openingTime: "8:00 AM - 6:00 PM",
        ticketPrice: "₹50 (Indians), ₹200 (Foreigners)",
        mapLocation: "https://maps.google.com/?q=Kanak+Vrindavan,Garden,Jaipur",
        bestTime: "October to March",
        duration: "1-2 hours",
        builtBy: "Maharaja Sawai Jai Singh I",
        builtIn: "1710",
        architecture: "Mughal garden with marble temples",
        significance: "Recreation of Vrindavan",
        photography: "Allowed",
        facilities: ["Garden", "Temples", "Fountains", "Parking", "Restrooms"]
    }
];
